name: Auto-Build PJSK RMSKIN

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repo Kopyala
      uses: actions/checkout@v4

    - name: Ana Dizindeki Tum Dosyalari RMSKIN Olarak Paketle
      run: |
        $workspace = "$env:GITHUB_WORKSPACE"
        $output = "$env:GITHUB_WORKSPACE\PJSK_Ultimate_Player.rmskin"

        Write-Host "Ana dizin arsivleniyor..."
        # .github klasorunu ve cikan rmskin dosyasini haric tutarak her şeyi ziple
        Get-ChildItem -Path $workspace -Exclude ".github", "PJSK_Ultimate_Player.rmskin" | Compress-Archive -DestinationPath $output -Force

        if (Test-Path $output) {
            Write-Host "RMSKIN basariyla olusturuldu!"
        } else {
            Error "Paketleme basarisiz oldu!"
            exit 1
        }

    - name: RMSKIN Dosyasini Artifact Olarak Yukle
      uses: actions/upload-artifact@v4
      with:
        name: PJSK-Ultimate-Player-RMSKIN
        path: PJSK_Ultimate_Player.rmskin
