name: Build PJSK GitHub Bundle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repo Kopyala
      uses: actions/checkout@v4

    - name: Tum Dosyalari (Logo, MP3, INI) Ziple
      run: |
        Compress-Archive -Path "PJSK_Custom\*" -DestinationPath "PJSK_Ultimate_Player.zip" -Force

    - name: Artifact Olarak Kaydet
      uses: actions/upload-artifact@v4
      with:
        name: PJSK-Bundle
        path: PJSK_Ultimate_Player.zip
